name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Push
        run: |
          docker login -u ${{ secrets.DOCKER_U }} -p ${{ secrets.DOCKER_DK }}
          docker build -t aljm/authoria-dns:latest .
          docker push aljm/authoria-dns:latest